Resources:
  SendAndLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendAndLogFunction
      CodeUri: .                        
      Handler: src/handler.sendAndLog
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          LOG_TABLE: EmailLogs
          SMTP_HOST: localhost # mudar para host do servidor postfix
          SMTP_PORT: 25
      Events:
        SendEndpoint:
          Type: Api
          Properties:
            Path: /send
            Method: POST
            Cors:
              AllowOrigins: "'localhost:3000'" # mudar para o domínio do frontend (cloudfront)
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
      Policies:
        - AmazonDynamoDBFullAccess
