Resources:
  SendAndLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendAndLogFunction
      CodeUri: .                        # <-- inclua isto
      Handler: src/handler.sendAndLog
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          SENDER_EMAIL: lucas@localhost
          LOG_TABLE: EmailLogs
          SMTP_HOST: 172.31.107.3
          SMTP_PORT: 25
      Events:
        SendEndpoint:
          Type: Api
          Properties:
            Path: /send
            Method: POST
            Cors:
              AllowOrigins: "'https://d32uo9ncvvsdm7.cloudfront.net'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
      Policies:
        - AmazonDynamoDBFullAccess
