Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SpoofingTestApi
      StageName: dev

  SendAndLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendAndLogFunction
      CodeUri: .
      Handler: src/handler.sendAndLog
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          LOG_TABLE: EmailLogs
          SMTP_HOST: localhost
          SMTP_PORT: 25
      Events:
        SendEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /send
            Method: POST
            Cors:
              AllowOrigin: "'http://localhost:3000'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: EmailLogs

  StartVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartVerificationFunction
      Handler: src/handler.startVerification
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          PIN_TABLE: PinVerifications
          SMTP_HOST: 172.31.107.3
          SMTP_PORT: "25"
      Events:
        StartVerifApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /start-verification
            Method: POST
            Cors:
              AllowOrigin: "'*'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
        StartVerifApiOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /start-verification
            Method: OPTIONS
            Cors:
              AllowOrigin: "'*'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: PinVerifications


  VerifyAndSendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VerifyAndSendFunction
      Handler: src/handler.verifyAndSend
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          PIN_TABLE: PinVerifications
          LOG_TABLE: EmailLogs
          SMTP_HOST: 172.31.107.3
          SMTP_PORT: "25"
      Events:
        VerifyAndSendApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /verify-and-send
            Method: POST
            Cors:
              AllowOrigin: "'*'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
        VerifyAndSendApiOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /verify-and-send
            Method: OPTIONS
            Cors:
              AllowOrigin: "'*'"
              AllowHeaders: "'Content-Type'"
              AllowMethods: "'OPTIONS,POST'"
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              - PinVerifications
              - EmailLogs
